CREATE TABLE order_bank.countries
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    deleted boolean NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    name VARCHAR(128) NOT NULL,
    code VARCHAR(3) NOT NULL
);

CREATE TABLE order_bank.addresses
(
    id VARCHAR PRIMARY KEY DEFAULT uuid_generate_v4(),
    deleted boolean NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_by VARCHAR(128),
    country_id INTEGER NOT NULL REFERENCES order_bank.countries (id),
    address VARCHAR(128) NOT NULL,
    zip_code VARCHAR(32) NOT NULL,
    city VARCHAR(64) NOT NULL
);

CREATE TABLE order_bank.orders_card_delivery
(
    id VARCHAR PRIMARY KEY DEFAULT uuid_generate_v4(),
    planned_delivery_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    first_name VARCHAR(64),
    last_name VARCHAR(64),
    middle_name VARCHAR(64),
    contact_phone VARCHAR(32),
    office_id VARCHAR,
    original_address_id VARCHAR REFERENCES order_bank.addresses (id),
    destination_address_id VARCHAR NOT NULL REFERENCES order_bank.addresses (id),
    person_type VARCHAR(20)
);

CREATE TABLE order_bank.orders_card
(
    id VARCHAR PRIMARY KEY DEFAULT uuid_generate_v4(),
    trace_id VARCHAR NOT NULL,
    user_id VARCHAR NOT NULL,
    status VARCHAR(15) NOT NULL,
    deleted boolean NOT NULL DEFAULT FALSE,
    request_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(128),
    comment VARCHAR(255) NOT NULL,
    card_id VARCHAR NOT NULL,
    card_type VARCHAR(20) NOT NULL,
    invoice_id VARCHAR UNIQUE,
    card_receiving_method VARCHAR(20) NOT NULL,
    order_card_delivery_id VARCHAR REFERENCES order_bank.orders_card_delivery (id),
    currency VARCHAR,
    balance NUMERIC(18, 4)
);