CREATE TABLE delivery_bank.countries
(
    id SERIAL PRIMARY KEY,
    deleted boolean NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),
    name VARCHAR(128) NOT NULL,
    code VARCHAR(3) NOT NULL
);

CREATE TABLE delivery_bank.addresses
(
    id VARCHAR PRIMARY KEY DEFAULT uuid_generate_v4(),
    deleted boolean NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(128),
    country_id INTEGER NOT NULL REFERENCES delivery_bank.countries (id),
    address VARCHAR(128) NOT NULL,
    zip_code VARCHAR(32) NOT NULL,
    city VARCHAR(64) NOT NULL,

    CONSTRAINT uk_address_city_country UNIQUE (city, address, country_id)
);

CREATE INDEX idx_addresses_city_country ON delivery_bank.addresses (city, country_id);

CREATE TABLE delivery_bank.couriers
(
    id VARCHAR PRIMARY KEY DEFAULT uuid_generate_v4(),
    deleted boolean NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),
    user_id VARCHAR NOT NULL UNIQUE,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    middle_name VARCHAR(64),
    busy boolean NOT NULL DEFAULT FALSE,
    contact_phone VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE delivery_bank.recipients
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    deleted boolean NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),
    user_id VARCHAR NOT NULL UNIQUE,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    middle_name VARCHAR(64),
    contact_phone VARCHAR(32) NOT NULL,
    office_id VARCHAR,
    person_type VARCHAR(20) NOT NULL
);

CREATE TABLE delivery_bank.card_deliveries
(
    id VARCHAR PRIMARY KEY DEFAULT uuid_generate_v4(),
    deleted boolean NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),
    planned_delivery_time TIMESTAMP WITHOUT TIME ZONE,
    order_id VARCHAR NOT NULL,
    card_type VARCHAR NOT NULL,
    recipient_id BIGINT NOT NULL REFERENCES delivery_bank.recipients (id),
    courier_id VARCHAR REFERENCES delivery_bank.couriers (id),
    courier_contact_phone VARCHAR(32),
    origin_address_id VARCHAR NOT NULL REFERENCES delivery_bank.addresses (id),
    destination_address_id VARCHAR NOT NULL REFERENCES delivery_bank.addresses (id),
    status VARCHAR(20) NOT NULL,
    delivery_duration INTERVAL,
    pickup_date TIMESTAMP WITHOUT TIME ZONE,
    delivered_at TIMESTAMP WITHOUT TIME ZONE
);