server:
  port: 8098

spring:
  application:
    name: ${SERVICE_NAME:office-service}

  datasource:
    url: ${OFFICE_DB_LOCAL_URL:jdbc:postgresql://${HOST:localhost}:${OFFICE_DB_PORT:5440}/${OFFICE_DB_NAME:office_db}}
    username: ${OFFICE_DB_USERNAME:postgres}
    password: ${OFFICE_DB_PASSWORD:postgres}

  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      org.hibernate.envers.audit_table_suffix: _history
      org.hibernate.envers.audit_table_prefix:
      org.hibernate.envers.default_schema: office_bank_history

  flyway:
    enabled: true

  data:
    redis:
      host: ${HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:secret}

user-service:
  jwt:
    secret: ${SECRET_KEY:MyVeryLongAndSecureSecretKeyForJWTTokenSigningThatIsAtLeast64CharactersLongToMeetHS512Requirements123456789}
  client:
    base-url: ${USER_CLIENT_BASE_URL:http://localhost:8091}
    api-key: ${INTERNAL_API_KEY:your-internal-api-key}
    x-internal-key: ${INTERNAL_KEY:X-Internal-Api-Key}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: true
  packages-to-scan: com.github.seecret1.office_service.controller
  paths-to-match: /api/v1/**

logging:
  config: "classpath:logback.xml"
  level:
    com.github.seecret1.office_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: ${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none

services:
  api-key: ${INTERNAL_API_KEY:your-internal-api-key}