global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'user-service:8091' ]

  - job_name: card-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'card-service:8092' ]

  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'order-service:8093' ]

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'payment-service:8094' ]

  - job_name: transaction-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'transaction-service:8095' ]

  - job_name: invoice-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'invoice-service:8096' ]

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'notification-service:8097' ]

  - job_name: office-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'office-service:8098' ]

  - job_name: office-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'office-service:8099' ]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: tempo
    metrics_path: /metrics
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: user-postgres
    static_configs:
      - targets: [ 'user-postgres-exporter:9187' ]

  - job_name: card-postgres
    static_configs:
      - targets: [ 'card-postgres-exporter:9187' ]

  - job_name: order-postgres
    static_configs:
      - targets: [ 'order-postgres-exporter:9187' ]

  - job_name: payment-postgres
    static_configs:
      - targets: [ 'payment-postgres-exporter:9187' ]

  - job_name: transaction-postgres
    static_configs:
      - targets: [ 'transaction-postgres-exporter:9187' ]

  - job_name: invoice-postgres
    static_configs:
      - targets: [ 'invoice-postgres-exporter:9187' ]

  - job_name: notification-postgres
    static_configs:
      - targets: [ 'notification-postgres-exporter:9187' ]

  - job_name: office-postgres
    static_configs:
      - targets: [ 'office-postgres-exporter:9187' ]

  - job_name: redis
    static_configs:
      - targets: [ 'redis:6379' ]

  - job_name: zookeeper
    static_configs:
      - targets: [ 'zookeeper:2181' ]

  - job_name: kafka1
    static_configs:
      - targets: [ 'kafka1:9092' ]

  - job_name: kafka2
    static_configs:
      - targets: [ 'kafka2:9093' ]

  - job_name: kafka3
    static_configs:
      - targets: [ 'kafka3:9094' ]

  - job_name: rabbitmq
    static_configs:
      - targets: [ 'rabbitmq:5672', 'rabbitmq:15672' ]