server:
  port: 8096

spring:
  application:
    name: ${SERVICE_NAME:invoice-service}

  datasource:
    url: ${INVOICE_DB_LOCAL_URL:jdbc:postgresql://${HOST:localhost}:${INVOICE_DB_PORT:5438}/${INVOICE_DB_NAME:invoice_db}}
    username: ${INVOICE_DB_USERNAME:postgres}
    password: ${INVOICE_DB_PASSWORD:postgres}

  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      org.hibernate.envers.audit_table_suffix: _history
      org.hibernate.envers.audit_table_prefix:
      org.hibernate.envers.default_schema: invoice_bank_history

  flyway:
    enabled: true

  data:
    redis:
      host: ${HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:secret}

  kafka:
    bootstrap-servers: ${HOST:localhost}:${KAFKA1_PORT:9092}, ${HOST:localhost}:${KAFKA2_PORT:9093}, ${HOST:localhost}:${KAFKA3_PORT:9094}
    ssl:
      enabled: ${KAFKA_SSL_ENABLED:false}
      trust-store-location: ${KAFKA_TRUSTSTORE_LOCATION:file:./kafka.truststore.jks}
      trust-store-password: ${KAFKA_TRUSTSTORE_PASSWORD:changeit}
      key-store-location: ${KAFKA_KEYSTORE_LOCATION:file:./kafka.keystore.jks}
      key-store-password: ${KAFKA_KEYSTORE_PASSWORD:changeit}
      key-password: ${KAFKA_KEY_PASSWORD:changeit}
      protocol: ${KAFKA_SSL_PROTOCOL:SSL}
      enabled-protocols: TLSv1.2,TLSv1.3

    # Security properties
    properties:
      security:
        protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      ssl:
        endpoint:
          identification:
            algorithm: ${KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:https}

user-service:
  client:
    base-url: ${USER_CLIENT_BASE_URL:http://localhost:8091}
    api-key: ${INTERNAL_API_KEY:your-internal-api-key}
    x-internal-key: ${INTERNAL_KEY:X-Internal-Api-Key}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: true
  packages-to-scan: com.github.seecret1.invoice_service.controller
  paths-to-match: /api/v1/**

logging:
  config: "classpath:logback.xml"
  level:
    com.github.seecret1.order_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: ${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none

app:
  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    topic: invoices
    request-topic: request-invoices
    orders-topic: response-orders
    retry-topic: retry-invoices
    group-id: invoice-group-id
    retry-group-id: invoice-retry-group-id
    dlt-topic: invoice.DLT
    dlt-group-id: invoice-group-id.dlt
    max-pull-records: 10
    partitions: 3
    replicas: 3
    timeout-seconds: 6

  retry:
    max-attempts: 3
    delay: 1500
    multiplier: 2
    max-interval: 10000
    timeout: 5

  invoices:
    limits:
      DEBIT:
        max-spending-limit: 200000
        commission-spending-limit: 100000
        description: "Дебетовая карта"
      DEBIT_PERSONAL:
        max-spending-limit: 300000
        commission-spending-limit: 200000
        description: "Именная дебетовая карта"
      CREDIT:
        max-spending-limit: 500000
        commission-spending-limit: 300000
        description: "Кредитная карта"

services:
  api-key: ${INTERNAL_API_KEY:your-internal-api-key}